### ISSUE TITLE
The calculation of currency revaluation is mismatched

### ISSUE THREAD

**Issue by asceticbs** [OCA/account-closing#126]
Dear Team,

We have faced an issue in the currency revaluation calculation.
You can find the attache file which can show the current result and the expected result.
 I would be thankful if any comment which can help to resolve this issue.

Kind Regards, Riken

[Currency reevaluation calculation.xlsx](https://github.com/OCA/account-closing/files/4014010/Currency.reevaluation.calculation.xlsx)

**Comment by asceticbs** [comment]
Anybody can help on this?
It seems the foreign balance does not calculate and stored in order to generate the Currency revaluation report in v12 Enterprise.

Regards,

**Comment by fclementic2c** [comment]
I see if one of my colleague can check this

**Comment by alexey-pelykh** [comment]
@asceticbs I've also encountered same (or at least similar issue) on bank accounts, this module just does not make any sense even when trying to test on runbot:
![image](https://user-images.githubusercontent.com/345102/102967369-103ade80-44f2-11eb-8586-2fea705b2251.png)
The starting balance of the USD account was US$0, ending is US$200, and ending in EUR has to be corrected from €95 to €80 (since exchange rate is 2.5 in demo data), so revaluation entry should've been €45 not €30.

(Unless I'm not missing anything)

**Comment by alexey-pelykh** [comment]
Oh dear, it counted only the entries with Partner being set, as if there has been only "Incoming 100 USD" transaction, and if it assumed that ending balance is US$100, then of course to get US$100/2.5 = €40 from original €100 it needs -€60 to balance it off. Oh dear, how others have been using this module 😱

**Comment by alexey-pelykh** [comment]
It seems that a fix has been proposed in https://github.com/OCA/account-closing/issues/117, will check it.

**Comment by alexey-pelykh** [comment]
Okies, to be more specific: code fails if bank account has both lines with partner and w/o partner

**Comment by alexey-pelykh** [comment]
Please see #149, with those changes results are as expected for the test case above:
![image](https://user-images.githubusercontent.com/345102/103069283-5b6ef300-45bf-11eb-8c00-9e5c17a61eaa.png)
