### ISSUE TITLE
IMP - [multi_currency_revaluation] when we repeat revaluation with same revaluation date , it should not create multiple exchange diff entry

### ISSUE THREAD

**Issue by bunhin** [OCA/account-closing#168]
When  we repeat revaluation with same revaluation date,  it is create other journal entry.

Expected
The previous created entry is revised or deleted when we do repeat the revaluation, so avoid multiple exchange entry created.
 
Spotted on V11, not try yet on v12 of v13 yet

**Comment by Fabrizio1305** [comment]
same issue on v15. 
I believe this is due to the fact that the revaluation should impact the account being revalued (eg. payable or receivable) and not a third party one (2331 in CH case):

(l10n_ch Chart of account)

                        LOSS    GAIN
Revaluation account    [    ]  [    ]
Provision B.S account  [2331]  [2331]     
It shouldn't be 2331 but the revalued account, the provision BS account shouldn't be mandatory
Provision P&L account  [3906]  [4906]

this way the total of the revalued account , will have the amount that has been already posted on a previous re-valuation, and the next one, even on the same date, will take that posted amount into account

**Comment by makayabou** [comment]
Does it occur when you click on cut-off on an move line ?
